[mypy]
strict = True
ignore_missing_imports = True
explicit_package_bases = True

[mypy-db.*]
ignore_errors = True

[mypy-settings]
ignore_errors = True

[mypy-models.*]
ignore_errors = True

[mypy-views.*]
ignore_errors = True
